#!/bin/sh

style=""
while getopts "s:i:" option; do
  case $option in
    s)
      style=$OPTARG;;
    i)
      sourcefile=$OPTARG;;
    \?)
      echo "Usage:"
      echo "    -s <file>: specify a header file that points to a style."
      exit;;
  esac
done

file=$(basename -- $sourcefile)
filename="${file%.*}"

rm -f tmp.html
rm -f "${filename}.html"

pandoc -f markdown -t html5 -o tmp.html $sourcefile
printf "%s\n%s\n%s\n%s\n%s\n%s\n"\
  "<body>"\
  "<pre class=\"timestamp\">DATE: ${filename:0:4}-${filename:4:2}-${filename:6:2}"\
  "TIME:      ${filename:8:2}:${filename:10:2}</pre>"\
  "<a class=\"go-home\" href=https://0xe1c411f.github.io/>〈 home</a>"\
  "$(cat tmp.html)"\
  "</body>"\
  > tmp.html

cat $style tmp.html > "${filename}.html"

rm -f tmp.html
